services:
  mongodb:
    image: mongo:latest
    container_name: goride-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: goride-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goride-backend
    ports:
      - "5002:5001"
    env_file:
      - ./backend/.env
    environment:
      # Overriding MONGO_URI to use the local container name instead of the cloud URI
      # If you want to use the cloud DB instead, comment out the line below
      - MONGO_URI=mongodb://mongodb:27017/goride
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - mongodb
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5002/api
        NEXT_PUBLIC_RAZORPAY_KEY_ID: rzp_test_SENj7Gukg5vBSe
        NEXT_PUBLIC_AWS_BUCKET_NAME: go-ride
        NEXT_PUBLIC_AWS_REGION: ap-south-1
        NEXT_PUBLIC_S3_HOSTNAME: go-ride.s3.ap-south-1.amazonaws.com
    container_name: goride-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
  redis_data:
