services:
  mongodb:
    image: mongo:latest
    container_name: goride-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: goride-redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: goride-backend
    volumes:
      - ./backend:/app
      - backend_modules:/app/node_modules
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3001
    depends_on:
      - mongodb
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5001/api
        NEXT_PUBLIC_RAZORPAY_KEY_ID: rzp_test_SENj7Gukg5vBSe
        NEXT_PUBLIC_AWS_BUCKET_NAME: go-ride
        NEXT_PUBLIC_AWS_REGION: ap-south-1
        NEXT_PUBLIC_S3_HOSTNAME: go-ride.s3.ap-south-1.amazonaws.com
    container_name: goride-frontend
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
      - frontend_next:/app/.next
    ports:
      - "3001:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
  redis_data:
  backend_modules:
  frontend_modules:
  frontend_next:
